### ISSUE TITLE
BleesEI - stage 2-3

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#102]
### Выбор метода решения

- "Метод решения - исполняемый сценарий. ...Скоростью разработки сценария; " -  приводимый аргумент достаточно сильный, но субъективный (важен только для автора статьи)
-  Реализуемые критерии проверки статьи - не хватает хотя бы маленького обоснования, почему вы выбрали именно их

### Описание метода решения

Основное замечание - так называемый "телеграфный стиль" изложения. Суть проблемы заключается в том, что 
- отдельные абзацы состоят только из одного предложения,
- большую часть составляют списки (вместо текстов)
- нет плавных текстовых переходов от одного подраздела к другому

### Аннотация

- "научному стилю" - можно без кавычек, с кавычками кажется, что вы используете термин  с негативным оттенком. 
- является ли "водность" текста (и по аналогии термин "вода") общеупотребительным ? Кажется что нет (но я не уверен до конца). Если это так, то давайте заменим на "долю вводных слов от общего числа"

### Выводы

- необходимо уточнить какие именно критерии использовались и какие предъявляются требования ко входным данным
- было бы здорово уточнить что программа выдает не бинарный признак (accepted | rejected), а отстраненные числовые показатели, интерпретация которых дело пользователя. 
- давайте наметим, какими (гипотетически) критериями было бы хорошо расширить инструмент.

**Comment by EduardBlees** [comment]
#127
