### ISSUE TITLE
KlimukKP - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#107]
### Вердикт

После тщательной обработки и исправления замечаний ниже статья может быть рекомендована к подаче на конференции ППС. 

### Введение

- "(по возможности и спроектировать)" - избегайте неуверенных формулировок подобного рода. В научной статье необходимо описывать фактические результаты, поэтому состояний может быть только два - вы спроектировали или вы не спроектировали. 

### Обзор

- "своими плюсы и свои минусы." -> достоинства и недостатки

### Выбор метода решения

"Решение представляет собой плагин для движка Unity" - в данном разделе из-за отсутствия связки с предыдущим разделом и необходимых обоснований ваших решений не понятно 1) почему вы решили решению быть плагином 2) для чего предназначено ваше решение?

### Описание решения

Давайте расширим первый абзац данного раздела, так как абзацы длинной менее трех предложений выступают для редакторов очень сильным раздражителем. 

Кроме того, начиная читать подразделы, становится не понятно, к чем относиться приведенный в них текст, хотя формально он соответствует требованиям из раздела выше. Кажется, что эту проблему можно решить введением подраздела (который необходимо расположить самым первым) "Архитектура решения", где было бы описано из чего ваше решение состоит, как взаимодействуют его компоненты, какие сценарии использования для решения характерны. Также очень большим шагом навстречу читателю будет добавление рисунка с макетом интерфейса пользователя для вашего плагина, так как в текущем варианте требуется очень многое представлять в уме. 

### Заключение

- Текущее решение  -> предложенное решение
- "оптимизация алгоритма" очень опасное утверждение, так как в такой формулировке это подразумевает математическое доказательство оптимальности решения. Предлагаю ослабить утверждение. 
- "В данный момент решение слабо отличается от аналогов, а потому требуется продумать и реализовать отличительные особенности от готовых решений." - данное предложение звучит как посыпание головы пеплом. Предлагаю его убрать.
- "В дальнейших планах" - данный раздел написан с точки зрения курсовой работы/отчета, но для научных статей такой план дальнейших исследований неприемлем, так как ключевое слово тут **исследование**. Предлагаю переформулировать его, оставив задачи по 1) разработке/доработке решения 2) экспериментального исследования свойств решения

### Утверждения, который не хватает обоснованности (например в виде ссылки)

Ниже несколько (но не все ) примеров утверждений, требующих обоснования:
- В современное время все чаще появляется необходимость в шейдерах, 
- Однако, сам процесс создания шейдеров требует знаний программирования шейдеров и происходит обычным написанием его в текстовых редакторах с подсветкой синтаксиса
- Зачастую это отнимает много времени,
- Вариантов использования шейдеров очень много и создать универсальный шаблон не получится

Также необходимо снабдить ссылками все упоминания возможностей существующих решений (Unity, Unreal Engine 4 , упоминаемые в тексте аббревиатуры)

### Общие замечания

- Избегайте помещения текста в скобки. Либо удалите его из текста статьи, если он не важен, либо замените скобки на другие знаки препинания.
- Не используйте сокращения: кол-во, пр., тд.
- Проверьте согласованность предложений текста, например, вычитав его кому-нибудь. Примеры, на мой взгляд, слишком длинных или не согласованных предложений:
-- Однако, сам процесс создания шейдеров требует ....
-- Процесс создания шейдеров в Unity зачастую требует больших ....
-- Далее описаны решения по поводу реализации требований.
- Только один элемент из списка литературы имеет ссылку в тексте. Необходимо либо убрать все не упомянутые элементы, либо сослаться на них.
- У рисунка и таблицы нет подписи.

**Comment by ChivaTateo** [comment]
Мои замечания на данный момент:
- Картинку вставил как пример. Потом поставлю другую, как только нарисую.
- Подписи к картинкам имеются, просто в md формате они не пишутся автоматически. Но pandoc их прекрасно выставляет в других документах

Из того что сделал:
- Поправил некоторые формулировки и исправил согласованность.
- В выборе решения добавил немного обоснования и сделал чуть согласованней
- Добавил подпункты в описание решения
- Почистил заключение
- Исправил литературы и добавил ссылки

Из того, что стоит сделать:
- добавить по каждой части интерфейса информацию. Тогда будет выглядеть более полно все.

Это все что успел сделать в общем-то на данный момент. Статья в любом случае будет еще корректироваться.
#213
