### ISSUE TITLE
GolubevVV - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#114]
### Вердикт 

Статья рекомендуется к подаче на конференцию ППС  (http://seim-conf.org/paper-submission/) после прохождения дополнительного рецензирования и исправления замечаний из данной задачи.

Аналоги

- ссылки на репозитории аналогов должны быть оформлены либо как элементы списка литературы, либо как сноски

Дополнительные рекомендации

Добавьте описание реального исследования работы вашего решения, либо на

**Comment by OvaUbe** [comment]
@zmm, либо на...?

**Comment by OvaUbe** [comment]
Done - https://github.com/moevm/scientific_writing-2017/pull/140.
Пофиксил обязательное замечание.
Рекомендацию обязательно уту, если вы не против, позже. Она не сделается за пару минут, а сейчас очень интенсивный график работы, и дедлайн по этой статье 19.12.

**Comment by anyfilatov** [comment]
abstract
* Первое предложение выглядит глупо. Расширьте его или замените
* После прочтения абстракта сложилось впечатление, что ROS - это средство визуализации и дебага для любого софта. Но это же неправда. Надо сказать про то, что ROS используется в робототехнике, полезен при отладке программ, которые доолжны запускаться на роботах

Intro
* Опять-таки вы наприаете на то, что ROS предоставляет хорошие методы отладки. Но ни слова не говорите о том, что ROS применяется исключительно в задачах робототехники. Кроме того в вашем повествовании угадывается мысль, что Robot operating system никакая не operating system, а какая-то утилита.
* в интро нет цели работы. Необходимо добавить

Requirements
* У вас есть слова "To follow ROS reactive workflow". Либо объясните неподготовленным читателям, что вы имеете ввиду, либо дайте ссылку на литературу
* To report swap space usage difference, for example. Предложение сказано слишком по-русски и слишком разговорно. Перефразируйте и объедините с предыдущим предложением
* Последний абзац в пунтке А. Непонятно, зачем он нужен. Какую мысль подтверждает и какой из этого следует вывод
* Пункт В. Первый абзац. Началось использование терминологии nodes+topics, в то время, как ни слова до того не было сказано про то, как устроен ROS. 
* Замечание по пункту А расширяется на пункты B,C,D. Вы пишете requirements, но при этом не формулируете требования по каждому перечисленному пункту. Складывается ощущение, что у вас требование - это соблюдение этих четырёх пунктов, а текст в этих подпунктах служит только для определения, что значат слова, стоящие в названии подпункта. Рекомендую в конце каждого подпункта написать по предложению, где описать как именно каждое требование может быть выполнено. Если вы хотите оставить это на пункт IV, тогда сделайте не в виде подпунктов, а в виде списка, где распишите подробнее каждый пункт. А то сейчас у вас есть бессвязные подпункты, не отвечающие на вопрос читателя, зачем это всё нужно

Implementation
* Вы напираете на слово асинхронный. В чём причина использрвания именно асинхронного наблюдения. Возможно имелось ввиду неблокирующее наблюдение?
* Если вы разработали какое-то ПО, крайне желательно показать какие-нибудь цифры, которое это ПО выдало. А то вы не показываете ни кода, ни результата работы и вообще не доказываете, что ваш подход работает. Крайне желательно добавить таблицу, где ваша тула напускается на какую-нибудь работающую ноду (ноды) и показать результаты применения

Conclusion
* Сначала пишете "the desired implementation", в следующем абзаце "current implementation". Пишите заключение в том ключе, что у вас уже есть реализация, описывайте, какая он молодец и что она уже умеет или не умеет делать. 
* Последнее предложение можно переформулировать в более стандартном виде. Кодовая фраза звучит примерно так. Future work is to do .. и далее по тексту

Referencies
* man? дайте хотя бы ссылку на онлайн описание. Конкретную. На худой конец на книгу по ROS, где такие слова встречаются

**Comment by OvaUbe** [comment]
Requirements:
> Началось использование терминологии nodes+topics, в то время, как ни слова до того не было сказано про то, как устроен ROS
Это первый опыт написания научных статей - правильно ли я понял по замечанию, что в таком формате нужно расписывать основы терминологии ROS, даже если сама статья посвящена узкому аспекту? Полагал, что достаточно ссылки (согласен, плохо, что даже ссылки нет).
Implementation:
> Вы напираете на слово асинхронный.
Привычна такая терминология. В некоторых экосистемах (boost.asio, например) организацию работы через observer pattern в общем случае обозначают asynchronous workflow.
> Возможно имелось ввиду неблокирующее наблюдение? 
Не совсем. Неболкирующее наблюдение может быть и с использованием `select(...)`, например. Но это не означает отсутствие поллинга. Имелся ввиду асинхронный интерфейс. Вот, видимо, это не совсем стандартный термин - мы привыкли использовать его на текущем проекте. Observer, signal - может, так понятнее?
References:
Всегда считал, что man (и проект man7 в том числе) являются авторитетными источниками. Это не так? Признаться, неожиданное замечание. Онлайн описания как раз таки менее авторитетны, это уж точно.

**Comment by OvaUbe** [comment]
@zmm, @anyfilatov, к слову, если никто не против - https://github.com/moevm/scientific_writing-2017/pull/140 можно помержить. Он фиксит отдельную мелкую проблему + там дополнения для скрипта оценивания. Эта isssue пока останется открытой.

**Comment by anyfilatov** [comment]
> Это первый опыт написания научных статей - правильно ли я понял по замечанию, что в таком формате нужно расписывать основы терминологии ROS, даже если сама статья посвящена узкому аспекту? Полагал, что достаточно ссылки (согласен, плохо, что даже ссылки нет).

В Интро посвятите абзац ROSу, опишите, что это такое и что за ноды и топики в нём есть

> Вот, видимо, это не совсем стандартный термин - мы привыкли использовать его на текущем проекте. Observer pattern, signal, reactive interface - может, так понятнее?

Можно оставить асинхронный, просто не очень понятно, зачем его использовать в принципе. Вроде достаточно сказать что-то вроде "необходимо уметь наблюдать" и так далее

> Пока нет - получил тему НИР в середине ноября. Там есть зачатки функционала, в принципе, можно выжать что-то по мелочи.

Если нет, то оставьте так, не придумывайте только из воздуха ничего

> Выглядит как неконсистентность. Но в первом случае я описывал выводы анализа желаемых фич, а во втором - то, что уже умеет текущая "поделка". Эта статья все же частично вводная, не про законченный проект.

Не согласен. Выводы делаются по уже проделанной работе. В любом случае лучше не писать "желательно, чтобы система обладала такими-то свойствами". Лучше сказать, что "были сформулированы такие-то свойства, которые должны выполняться для хорошего и правильного решения поставленной задачи"

> Всегда считал, что man (и проект man7 в том числе) являются авторитетными источниками. Это не так? Признаться, неожиданное замечание. Онлайн описания как раз таки менее авторитетны, это уж точно.

Никогда не видел в научных статьях ссылки на man-ы. Либо книги, либо электронные ресурсы. Найдите описание стандарта, пусть даже в электронном виде.

**Comment by OvaUbe** [comment]
Спасибо за развернутый ответ, постараюсь все учесть до 22.12

**Comment by OvaUbe** [comment]
Done - #140.
Разбил фиксы замечаний по отдельным коммитам в сабмодуле, чтобы удобнее было ревьюить.
