### ISSUE TITLE
MokretsovRM - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#115]
### Общий вердикт

Статья рекомендуется к подаче на конференцию ППС после полного и тщательного исправления указанных ниже замечаний. 

### Название 

- В названии и тексте встречается слово "уникальная", которое в данном контексте добавляет оттенок рекламного сообщения ("не имеющий аналогов фильтр для воды", "самый вкусный корм для собак"). Кажется, что данный эпитет не проясняет картины (очевидно, что все платформы не являющиеся уникальными, являются плагиатом), поэтому предлагаю его удалить. Без него название и текст только выиграют. 

### Введение

Очень сильно не хватает ссылок, подтверждающих утверждения из начала раздела.

### Сравнение аналогов

Не хватает:
- чуть более длинного связующего текста в самом начале раздела
- описания принципа подбора аналогов и в целом обоснования - почему аналоги из двух разных групп
- ссылок на источник про каждый из аналогов
- длины разделов. Короткие (< 3 предложений) разделы вызывают у редакторов очень плохую реакцию. Поэтому, их нужно ли распространить, либо совместить вместе.
- связующие слова в "Критерии сравнения аналогов ..." - важно показать как критерии связаны с целью. 

### Архитектура платформы

- для лучшего понимания идеи статьи нужно добавить для схемы архитектуры предлагаемого решения обоснования (почему решили делать так).
- также было бы здорово добавить немного общих слов которые связывают вашу идею с результатами обзора. 
- в разделе Генератор квестов не хватает рисунков, которые бы графически иллюстрировали идеи работы этой части системы - какие маршруты хорошие, а какие плохие?
- рассчитываемого специальными способами. - поясните и дайте ссылку на инструмент.
- Web-interface 
-- добавьте рисунок с хотя бы примерным макетом этого интерфейса
-- -> веб-интерфейс
- База данных (MongoDB) ->  База данных
- Сгенерированные приложения. 
-- Кажется, что в этом разделе можно более детально описать процедуру формирования приложения-квеста.
-- добавьте слова про сами приложения (как будет выглядеть шаблон, что будет варьироваться и почему) и про частичную апробацию со ссылками на уже опубликованный прототип. 

### Заключение

Не хватает: планов на будущие исследования, недостатков архитектуры, слов про уже опубликованные приложения.

### Общие замечания:

- ссылки необходимо разместить в конце статьи, каждая должна иметь как минимум одно упоминание в тексте.
- для лучшего понимания идеи статьи нужно добавить для схемы архитектуры предлагаемого решения обоснования (почему решили делать так).

**Comment by dartl** [comment]
Правки внес

**Comment by dartl** [comment]
#139 
#143

**Comment by zmm** [comment]
:+1:
