### ISSUE TITLE
KuzminME - paper 

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#116]
Вердикт

Статья рекомендуется к подаче в Известия ЛЭТИ, либо на очередную конференцию FRUCT ( требует перевода на английский)/SEIM (тоже требует перевода для включения публикации в индексы) после дополнительного рецензирования специалистом по предметной области. 

Недостатком  работы на данном этапе является отсутствие ссылок на подтверждающие материалы для утверждений в разделе Введение.

Дальнейшие действия такие:
- вы исправляете замечание выше,
- оформляете статью в шаблон журнала/или конференции 
- прикладываете ссылки на оформленную PDF статьи и добавляете label ready_for_check
- я добавляю в assignee рецензента, он выдает вам дополнительные комментарии.

**Comment by MaxGsomGsom** [comment]
Мне потребуется время для перевода на английский язык.

**Comment by MaxGsomGsom** [comment]
Мне потребуется время, чтобы перевести статью. Думаю подавать ее в FRUCT.

**Comment by zmm** [comment]
Учитывая, что перевод требует времени, предлагаю вас дополнительно прорецензировать по его окончанию.
