### ISSUE TITLE
AlekseevichAS - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#134]
### Общий вердикт

Статья рекомендуется к подаче на конференциюю ППС после исправления замечаний ниже.

### Аннотация и Введение

- Первый абзац аннотации  дублирует первый абзац Введения. Необходимо его переписать так, чтобы это совпадение исчезло.
- "разработка речевого пользовательского интерфейса, чтение произвольного текста без предварительной разметки. Данные проблемы весьма актуальны для людей с ограниченными возможностями." - кажется, что слово "проблема" здесь не совсем уместно, так как  разработка речевого интерфейса как проблема это проблема для программистов, а пользователей интересует наличие/удобство/цена/качество работы таких интерфейсов. 
- сформулируйте цель работы явно. 

### Сравнение аналогов

Дайте в самом начале данного раздела краткое пояснение по какому принципу и из каких категорий вы будете выбирать аналоги для сравнения.

### Критерии сравнения аналогов

- Редакторы очень не любят разделы состоящие из 1-2 предложений - это производит впечатление натянутости формулировок. Поэтому предлагаю вам либо добавить больше обоснований для каждого критерия (почему он важен), либо переформатировать раздел так, чтобы в нем не было маленьких подразделов.
- Скорость какого процесса имеется в виду? Как она измеряется?
- Качество синтеза - кажется, что  вы оцениваете не значение данного критерия, а зависимость его значения от внешних факторов.

### "Определение[5]".

Данный раздел представляет собой дословную копию соответствующего раздела из источника [5], которая в свою очередь цитируется в неизменном виде в большом количестве интернет-источников. При этом сам раздел не несет никакой функциональной нагрузки:
- на него нет прямых ссылок
- никак не используется определение суффиксного дерева.
Такой раздел будет трактован редакторами как попытка повысить объем статьи.

Я рекомендую удалить данный раздел и, если это действительно необходимо, сделать краткую пометку в конце предыдущего раздела про то, что вы будете использовать определение из источника 5.

### Отсутствуют ссылки

Ниже примеры (не все) на упоминаемые понятия, для которых не дается ссылка на литературу:
- Unit Selection
- алгоритм Ханта-Блэка 
- Алгоритм Витерби
- MFCC, PCT, MSE, ...

### Общие замечания

- часть элементов списка литературы не упоминается в тексте. Либо удалите эти элементы, либо добавьте ссылки. 
- в вашей работе очень много текста в скобках. Либо удалите его, либо замените скобки на запятые. В текущем варианте он демонстрирует редактору неуверенность в описанных результатах.

**Comment by MagisterDemens** [comment]
Постарался исправить все озвученные замечания. https://github.com/moevm/scientific_writing-2017/pull/161
[paper.pdf](https://github.com/moevm/scientific_writing-2017/blob/7d2cfa9398bbab60f4bf5cb817d7b9d8a8d0aad3/2381/AlekseevichAS/paper.pdf)

**Comment by zmm** [comment]
Принято. 
Проверьте картинки в PDF - они у вас местами вылезают за край + кое-где осталась родная подпись.
