### ISSUE TITLE
ChulanovAA - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#135]
### Общий вердикт

Статья рекомендуется к подаче на конференцию ППС после исправления замечаний ниже.

### Введение

- Я очень рад, что вы прислушались к моему замечанию по поводу формулировки проблемы, однако я специально привел немного шуточный пример, для лучшего понимания. Предлагаю (уже серьезно) заменить формулировку на "сложность поиска музыкальных произведений, удовлетворяющих вкусам конкретных пользователей". Для усиления этого и следующих утверждений я рекомендую вам поискать статьи/статистические отчеты, в которых приводятся факты в защиту вашей точки зрения, например количество поисковых запросов на тему поиска музыки, опросы и тд.
- "Существующие решения либо не могут охватить все возможные предпочтения пользователей, либо работают недостаточно быстро" было бы здорово дать обоснование и к этому утверждению, так как оно достаточно сильное. 

### Сравнение аналогов

 Расчет низкоуровневых параметров является медленным по сравнению с другими аналогами в связи с необходимостью получения высокоуровневых параметров (жанра, ритма и т. д.) с помощью классификации. - требуется либо более детальное обоснование, либо ссылка на подтверждающий источник.

### Описание метода решения

В данном разделе присутствует некоторая недосказанность - вы описываете метод, однако:
- описывается только метод индексирования музыкальных композиций на основе их характеристик и это явно не формулируется;
- не понятно, как будет происходить поиск, а именно как вы будете сопоставлять между собой аудиозаписи (по какому алгоритму);

### Поэтому, предлагаю:
- явно назвать алгоритм индексирования,
- описать алгоритм сравнения аудиозаписей,
- добавить оба алгоритма на псевдокоде в конце раздела,
- возможно, добавить туда же какие-нибудь подитоживающие слова.

### Пожелание

Вы вскользь упоминаете обучающую базу, однако она является достаточно важным компонентом вашего решения. Я предлагаю вам в какой-то форме чуть подробнее охарактеризовать эту базу:
- из чего она формируется?
- как в ней хранятся отдельные композиции?
- какие форматы аудио-файлов можно использовать?

От этого описания ваша статья существенно выиграет. 

### Общие замечания

- не хватает ссылок к следующим терминам/понятиям
-- STFT - Short-Time Fourier Transform)
-- PCA - Principal Component Analysis
-- окно Ханна (Хеннинга),
- в вашей работе очень много текста в скобках. Либо удалите его, либо замените скобки на запятые. В текущем варианте он демонстрирует редактору неуверенность в описанных результатах.

**Comment by Dron642** [comment]
#145

**Comment by zmm** [comment]
Поздравляю, вы успешно исправили замечания!
