### ISSUE TITLE
KomarovDN - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#155]
Общий вердикт

Статья рекомендуется к подаче на конференцию ППС после исправления замечаний ниже.

Аннотация

Данная статья посвящена проблеме сложности создания 3D видеороликов с точки зрения потребителя - но ведь у нас речь идет не просто про абстрактные ролики, а про вполне конкретные и про их автоматическое создание. Давайте здесь уточним, что речь идет о трейлерах, иначе из аннотации читатели будут думать, что вы сделали нейроинтерфейс, который по мыслям пользователя идеально точно снимает для него фильм :) 

Введение

- затраченное время на создание которых обратно пропорциональны, низкая стоимость влечет за собой увеличение времени и наоборот. - добавьте пожалуйста подтверждающую ссылку.
- Создание 3D видеороликов в хорошем качестве требует больших ресурсных, вычислительных и временных затрат, необходимо найти - кажется что лучше последнюю запятую заменить на точку

Обзор предметной области

- заказчика\потребителя - выберите один термин.
- В идеальном мире, профессиональный дизайнер  ...  - данное утверждение написано с большой долей иронии (хотя я согласен, что от первого до последнего слова все правда). Предлагаю сформулировать его чуть менее едко. 
- Инструмент создания презентаций - необходимо дать ссылку на каждый из упоминаемых инструментов.
- Сделать самому в 3D редакторе
-- нужно дать ссылку на упоминаемые редакторы.
-- давайте назовем этот вариант более нейтрально 
- Соответствие требованиям - данный критерий звучит очень расплывчато. Давайте его либо конкретизируем либо уточним. 
- Стоимость - стоимость какая: денежная, вычислительная, поддержки?

Описание метода решения

- Основной функционал приложения - такое название представляет собой технический жаргон. может быть заменм его на "Интерфейс пользователя".
- давайте в целом добавим в этом разделе больше обоснований ваших решений, пока он выглядит очень ультимативно (особенно в разделе Используемые технологи)

Сравнение результата с аналогами

Добавьте вывод.

Заключение

Целью исследования было - давайте уберем тире, оно вносит какой-то неправильный смысл в первое предложение.

Общие замечания

- кажется, что слово ролик является жаргонизмом. Может быть использовать какой-нибудь более точный термин, например видео/видеофрагмент ?
- очень много разделов, состоящих из двух или менее предложений. Такие разделы необходимо либо объединить между собой, либо добавить в них больше текста - редакторы очень неприятно реагируют на них. 
- размер и количество картинок (особенно скриншотов) могут произвести впечатление попытки повысить объем. Давайте ограничим их количество четырьмя и соответственно, уменьшим их размер в четыре раза.

**Comment by komarkom** [comment]
Вопрос по картинкам. Могу я объединить 4 картинки в плитку? Будет это  считаться все равно четырмя картинками?

 Как правильно дать ссылку на -  Инструмент создания презентаций - необходимо дать ссылку на каждый из упоминаемых инструментов.

**Comment by zmm** [comment]
:+1:
