### ISSUE TITLE
SkorospelovLA - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#166]
### Общий вердикт
 
Статья рекомендуется к подаче на конференцию ППС после исправления замечаний ниже, 

### Аннотация

- предлагающих осуществлять -> осуществляющих
- В данной работе представлен проект сервиса с использование фильтрации на основе контента, в котором пользователю предлагается самостоятельно осуществлять регулировку параметров для поиска музыки. - добавьте после этого предложения ответ на вопрос - а чем же вам сервис лучше описанных аналогов.

### Актуальность

- Обычно, после аннотации идет раздел Введение. Он содержит в себе помимо актуальности еще и информацию о целях и задачах вашего исследования. 
- Текущие рекомендательные системы для поиска музыки, использующие коллаборативную фильтрацию, значительно превосходят по своей распространенности рекомендательные системы на основе контента, - дайте подтверждающую ссылку
- Отсутствует система... - а в чем собственно проблема в данном случае? Покажите противоречие.
- проблема холодного старта, разреженности данных и синонимии. - ссылка

### Сравнение аналогов

- в конце аннотации у вас молниеносный переход к "Сравнению аналогов", при этом совершенно не ясно, почему нужно их сравнивать? Добавьте текстовую связку.
- опишите отдельным абзацем, почему для сравнения были выбраны именно эти аналоги.

### Критерии сравнения аналогов

- Критерии должны быть привязаны к цели вашей работы. 
- "проблемой холодного старта" - кавычки не нужны.
- Таблица сравнения по критериям - таблице нужна подпись (заголовок нужно убрать)

### Выбор метода решения

- Приведите пожалуйста четкую формулировку того, чем ваше решение должно быть - веб-сервисом, мобильным приложением и т.д.
- С одной стороны, ... с другой ... - лучше разделить это на два требования или убрать данный оборот, так как он допускает неопределенность.

### Общий обзор метода решения

Кажется, что содержимое этого подраздела можно переместить в "Выбор метода решения".

### Особенности метода решения

- Таким образом, стек технологий должен предлагать лёгкую масштабируемость в случае увеличения нагрузки, а также простоту в использовании и реализации. - это очень резкое утверждение (самое главное не очень понятно исходя из чего должно быть так и к чему относится). Добавьте в него плавности.
- Плюсом является направленность на технологии с открытым исходным кодом по внутренним убеждениям авторов статьи. - плюсом для чего/кого? слова про убеждения авторов лучше заменить на более предметное утверждение.
- остается не ясным,  как именно будет технически реализовано извлечение из музыкальных композиций их характеристик. Раскройте пожалуйста этот вопрос хотя бы кратко. 

### Выводы

- Перспектива разработки -> дальнейшие исследования
- а далее - остальные пункты, описанные в разделе "Описание метода решения".  - кажется, что лучше либо конкретно расписать какие будут пункты, либо убрать эти слова, так как они могут быть негативно восприняты редактором.

**Comment by LeoSko** [comment]
Поправил всё, кроме переноса "Общего метода решения" в "Выбор метода решения" - в этом разделе всё же поясняется уже выбранное ранее решение, а не формулируется каким оно должно быть. Если всё же видится, что должно быть по-другому - перенесу.
#195 
paper.md - https://github.com/moevm/scientific_writing-2017/blob/master/2303/SkorospelovLA/paper.md

**Comment by zmm** [comment]
:+1:
