### ISSUE TITLE
AndrosovVU - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#192]
Общий вердикт

Статья требует тщательного исправления замечаний, после чего ее можно подать на конференцию ППС. 

Структура 

- Отсутствует раздел Введение, в котором должны быть сформулированы проблема, цель, задачи и актуальность.
- В тексте статьи отсутствует собственно таблица сравнения.

Обзор предметной области и Критерии сравнения аналогов

- Оба раздела начинаются "с места в карьер" - в начале каждого из них не хватает какого-то вступления, объясняющего зачем нужно сравнивать аналоги и почему для этого нужны какие-то критерии.
- описание аналогов 
  - реализовано очень разнородно - вы характеризуете аналоги очень по разному. Предлагаю по возможности унифицировать этот формат.
  - сам текст описания написан очень "телеграфно" - предложения кажутся не связанными друг с другом, как будто это выписка из личного дела (Языки: Английский + Субтитры. Сертификат об окончании.)
  - подподзаголовок Описание не нужен. 
  - Онлайн-школа Android-разработчиков [6] - данное описание очень сильно напоминает рекламу, рекомендую его направить в сторону описаний фактической стороны курса.
  - отличный первый шаг  - отличный это субъективная оценка, ее необходимо убрать.
  - По окончанию обучения вы получите - по окончанию .. учащиеся получают
- Критерии сравнения аналогов - помимо вводного текста необходимо также описать привязку критериев к цели.
-  xMOOC - дайте расшифровку и ссылку на какое нибудь определение данного термина. 
- Данный критерий не является обязательным - либо не приводите критерий, либо не пишите, что он не обязательный.
- Проверочные задания - редакторы очень не любят подразделы состоящие только из списка / начинающиеся со списка. Это чувство вызвано тем, что отсутствие поясняющего текста заставляет читателя делать умственное усилие для понимания такой особенности повествования, что читатели делать не любят. 
- etc - убрать

Описание метода решения

- Задачи на формирование частного ответа: есть входные данные А и Б, необходимо сформировать запрос, который решает поставленную задачу; - запрос ли ? может быть лучше заменить на более общий термин?
- Существует несколько методов проверки корректности таких задач - ссылка 
- Существует ряд основных стратегий обучающихся для решения задач на реализацию программного модуля: 
  - ссылка
  - используется ли эта классификация в дальнейшем тексте?
- По способу проверки корректности решения многошаговые задачи делятся на 2 основные методики: - ссылка
- Методика состоит в построении модели + В рамках проверки задач для онлайн-курса  - добавьте перед этими абзацами какие-нибудь подитоживающие слова, чтобы читатель понял, что это и есть предлагаемый вами результат.
- хочется увидеть хотя бы теоретические, хотя бы прикидочные технические подробности:
  - какая будет виртуализация?
  - как будете билдить?
  - примерно как будут устроены задания и проверки в них?
  - примеры формулировок.

Выводы

- ожидается сокращение временных затрат на проверку задач - этот вопрос не освещен в "Описание метода решения" и сам факт сокращения не обоснован.

Общие замечания

- Очень много разделов, состоящих из двух или менее предложений. Такие разделы необходимо либо объединить между собой, либо добавить в них больше текста - редакторы очень неприятно реагируют на них.
- В вашей работе в заметных количествах присутствует текст в скобках. Либо удалите его, либо замените скобки на запятые. В текущем варианте он демонстрирует редактору неуверенность в описанных результатах.

**Comment by rosshkaa** [comment]
https://github.com/moevm/scientific_writing-2017/pull/216
