### ISSUE TITLE
EfremovMA - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#203]
Общий вердикт

Статья рекомендуется к подаче на конференцию ППС после исправления замечаний ниже. 

Аннотация

- на обнаружение критических для производительности мест - кажется что лучше заменить слово "место" на более научный, например "элемент архитектуры", "фактор"  и так далее.
-  в наиболее пригодной архитектуры для рассматриваемых фреймворков: многоагентной. -  для согласованности текста будет лучше переписать это предложение так, чтобы в нем не было двоеточия.
- стоит  - необходимо
- различных характеристик производительности распределенной системы

Введение

- Объектом исследования данной статья являются многоагентные фреймворки для разработки ПО для автономных роботов (далее "фреймворки") на предмет критичных для производительности аспектов многоагентных робототехнических фреймворков. - кажется что это предложение не согласовано
- Кроме того, в состав фреймворков идет - входит
- На рынке доступны.. - а как быть с открытыми решениями? они по определению не могут быть "на рынке"

Обзор предметной области

- На каждый из рассматриваемых аналогов должна быть ссылка.
- в характеристиках аналогов часто встречаются субъективные оценки:
  - наиболее распространенный фреймворк
  - не очень популярный и разрабатывается медленно разрабатываемый
  - сложный для понимания корейский фреймворк
Либо подтвердите эти мнения ссылкой на рейтинги, либо не делайте подобных утверждений.

Ввиду незрелости разработки, в данной работе этот фреймворк рассматриваться не будет.  -  если так, то и упоминать о нем в статье не стоит.

Описание метода решения

Вы приводите области, которые могут влиять на производительность, но при этом не даете обоснований из источников.

Заключение

- (возможно, гибридная) - лучше убрать этот текст, или убрать скобки. 
- В данной работе и не рассматривалось некоторое количество фреймворков из-за централизованной архитектуры. - данное предложение лучше исключить.

Общие замечания

- Не все элементы списка литературы упомянуты в тексте. Либо удалите не упомянутые, либо добавьте ссылки в тексте.
- В тексте встречаются просторечные/не вполне научные слова и обороты, которые рекомендуется заменить на более наукообразные термины:
  - нету
  - стоит
  - места
  - на предмет
  - критичные
- в части предложений не согласованы окончания / рода /падежи.

**Comment by JAkutenshi** [comment]
Внесены изменения в соответствии с прикладываемым описанием #214

#### Аннотация

+ Заменено на: "Данная статья делает упор на обнаружение критических областей для производительности в многоагентной архитектуре, так как подобный подход является наиболее пригодным для разработки рассматриваемых робототехнических фреймворков."
+ См. пред. пункт.
+ Заменено.
+ "различных характеристик производительности распределенной системы" - не очень понял: что здесь не так?

#### Введение

+ Заменено на "...с целью установления важных для производительности элементов системы".
+ Заменено.
+ Идея такова, что рынок - не только про торгово-денежные отношения, а про любые добровольные отношения. И с точки зрения стоимости предложения - рыночные отношения от этого не пропадают, как и рынок. Кроме того, в терминологии Эрика  Рэймонда, производство открытого/свободного ПО как раз похоже на "базар". Тем не менее, я изменю формулировку на "Для программирования роботов доступно множество различных версий фреймворков с разными принципами работы...". Хотя я и не согласен с этим пунктом.

#### Обзор предметной области

+ Добавлены ссылки на проекты.
+ в характеристиках аналогов часто встречаются субъективные оценки:
    + (наиболее распространенный фреймворк) - заменено на "один из наиболее распространенных"
    + (не очень популярный и разрабатывается медленно разрабатываемый) - скорее-всего я убрал из-за пункта ниже, в статье такого больше нет.
    + (сложный для понимания корейский фреймворк) - убран из рассмотрения
 Либо подтвердите эти мнения ссылкой на рейтинги, либо не делайте подобных утверждений.
+ Фреймворки RoboComp и OpRos убраны из рассмотрения: первый по незрелости , которую сложно оценить, второй из-за нерабочего сайта и отсутствия кода.

#### Описание метода решения

+ Тут есть два возражения. Первый состоит в том, что источник дан в самом начале, это основная статья для данной работы: [Robotics software frameworks for multi-agent robotic systems development]. Во-вторых, я старался делать в конце каждого аспекта вывод о том, как каждый из них влияет на производительность. В противном случае моя работа будет чем-то вроде реферата. Возможно, требуется как-то лучше расставить ссылки, возможно, найти дополнительные подтверждения моим словам. Уточните, пожалуйста, как лучше.

#### Заключение

+ (возможно, гибридная) - лучше убрать этот текст, или убрать скобки.
+ Мне кажется это предложение важным, так как оно отражает возможный недостаток статьи. Возможно, это не является недостатком, т.к. само название статьи уточняет, что рассматриваются только многоагентые фреймворки. Если это так - тогда можно убрать весь абзац. Хотелось бы уточнить этот момент.

#### Общие замечания

+ Такого быть не может, т.к. используется biber с bibtex и литература добавляется только если на нее ссылаются. Возможно, Вы смотрели odt файл?
+ В тексте встречаются просторечные/не вполне научные слова и обороты, которые рекомендуется заменить на более наукообразные термины:
    + нету (заменено на отсутствует)
    + стоит (заменено на необходимо и требуется)
    + места (заменено на области и элементы системы)
    + на предмет (заменено на "с целью установления")
    + критичные == критический? Конкретно критичный был заменен на значительный или важный.
+ В ходе вычитки были исправлены как ошибки согласования, так и несколько фактических ошибок, допущенных из-за плохой вычитки.

Итоговый документ прикреплен.
[paper.pdf](https://github.com/moevm/scientific_writing-2017/files/1580942/paper.pdf)
