### ISSUE TITLE
StarikovNS - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#206]
Общий вердикт

Статья рекомендуется к подаче на конференцию ППС после исправления замечаний ниже.

Аннотация

Добавьте чуть больше деталей про то, какую задачу вы решали - иначе не очень понятно, что именно за решение вы сделали. 

Введение

- Первый абзац введения подозрительно напоминает аннотацию, перепишите его пожалуйста. 
- Основной проблемой является создание достаточно удобного подхода построения и взаимодействия объектов на сцене виртуального окружения при помощи компьютерного зрения - добавьте пожалуйста немного технических деталей про то, как, где и для кем этот подход используется + очень кратко скажите, как будет технически выглядеть ваше решение (Приложение, библиотека, патч ...)
- Дайте ссылки, подтверждающие актуальность решаемой задачи.

Обзор средств

- кажется, что помимо алгоритмов, существуют как минимум демонстрационные решения для вашей задачи. 
- был выбран алгоритм LBP, так как он является более быстрым в сравнении с алгоритмом Виолы–Джонса - дайте ссылку, подтверждающую этот факт.
- нет необходимости давать столь подробную характеристику Unity - достаточно дать ссылку. 

Общие замечания

- Является ли термин "Виртуальное окружение" устоявшимся? Если да, то дайте ссылку на источник с определением, иначе дайте свое определение явно во введении, так как сейчас первая ассоциация это https://lancelote.gitbooks.io/intermediate-python/content/book/virtual_environment.html.
- При первом упоминании каждой технологии необходимо давать ссылку на источник с ее описанием. 
- Местами текст вашей статьи страдает от “телеграфности” - предложения кажутся отрывистыми, не связанными друг с другом и манерой изложения напоминают сводки боевых действий (Враг занял левый берег Волги. Моральный дух личного состава высокий. В атаку идем по расписанию.). Примеры:
  - Создать прототип взаимодействия в среде виртуального окружения жестами рук.
  - В рамках работы были пройдены этапы анализа предметной области.

**Comment by nikgoust** [comment]
## Аннотация
Добавил деталей.
## Введение
Переписал первый абзац, добавил технических деталей. Не совсем понял про ссылки. Искал статьи где бы использовалось компьютерное зрение и виртуальное пространство, но к сожалению не нашел. Так же не существует "официальных" решений данной задачи.
## Обзор средств
Тоже не совсем понял что нужно добавить или описать?
Добавил ссылку.
Уменьшил описание в два раза, но полностью не убрал (что б было хотя бы поверхностное описание и больше знаков)
## Общие замечания
Изменил на "виртуальное пространство" и добавил ссылку в ведении.
Дал ссылки на офф сайт.
Примеры исправил, больше, вроде, не нашел (кроме перечислений, но там так вроде и должно быть?)
