### ISSUE TITLE
RazmochaevaNV - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#28]
- Описание актуальности проблемы в problem.md. Описывать актуальность это хорошо и правильно, но ответ на вопрос - в чем состоит решаемая проблема наверное не должен ее включать.   
- Актуальность в принципе - возможно, что прогнозы построенные нейронной сетью смогут обладать каким-то дополнительными качествами, нежели избавление сотрудников от дополнительной работы. 
- С точки зрения исследования нас интересует только ассортимент и связанные с ним свойства точки розничной торговли, поэтому предлагаю сузить до них "Объект исследования".

**Comment by NataRazmochaeva** [comment]
Спасибо за комментарии! :)
Внесла изменения:
https://github.com/moevm/scientific_writing-2017/pull/49

**Comment by NataRazmochaeva** [comment]
Спасибо за комментарии!
Внесла изменения:
https://github.com/moevm/scientific_writing-2017/pull/49
