### ISSUE TITLE
EfremovMA - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#29]
- Общее замечание - в ответе на ключевые вопросы вы пишите "Фреймворки для автономных роботов", но из такой фразы очень сложно понять для чего на самом деле служат фреймворки. Поскольку эта фраза выступает синонимом ключевого понятия вашей статьи, она должна быть семантически гладкой. Поэтому, дополните пожалуйста по тексту эту фразу недостающим словом - это сделает работу более читаемой. Например: фреймворки для **дрессировки/выращивания/ловли** автономных роботов :)
- Проблема и цель имеют слишком узкую направленность - получить значения производительности, но даже из ваших планируемых результатов ясно, что сама по себе (без точки отсчета) производительность не интересна, а интересно понять 
-- какой фреймворк является наиболее быстрым
-- как оценивать производительность у подобных фреймворков
Поэтому рекомендую вам переформулировать цель/проблему исходя из этих вопросов. помните что цель и проблема в работе - одна. 

- Аналоги - я бы добавил в качестве критерия что-то более связанное с исследованием производительности, например наличие примеров/поддержка общих для предметной области датасетов и т.д.

**Comment by JAkutenshi** [comment]
#181 Статья была почти полностью переписана, с учетом Ваших замечаний.

К сроку дедлайна я успел подготовить только .odt файл, но у меня есть желание оформить статью при помощи LaTeX в формате IEEE Conference. Я могу сделать это в ближайшие несколько часов? После внесений правок и исправлений все будет правиться в tex файлах в отдельной директории. Спасибо.

**Comment by JAkutenshi** [comment]
#191 Подтверждаю завершение создание LaTeX версии статьи. paper.pdf продублирован на всякий случай в корневой директории. 

Настоятельно рекомендую читать именно pdf, т.к. при работе с TeX-ом использовался спеллчек, было исправлено приличное количество поечаток, а так же добавлен пропавший столбец второй таблицы.
