### ISSUE TITLE
KuzminME - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#31]
Не совсем понятно что означает зачеркнутый текст. Если он соответствует тому, чего не будет в статье, то лучше его убрать совсем, иначе - сделать не зачеркнутым. 

**Цель**

Кажется, что для цели больше подходит такая формулировка (варианты через слеш даны, тк я не совсем погружен в область) - "Создание фреймворка/методики для исследования точности/оценки производительности/  алгоритмов MRSLAM".

**Актуальность**

Более расхожим термином является SLAM, возможно стоит дать расшифорвку для MRSLAM и кратко объяснить почему именно этот клас методов, а не какой нибудь другой *SLAM.

**Предмет исследования** в целом хороший, но для большей лаконичности я бы все перечисленное постарался объединить одной фразой.

**Comment by MaxGsomGsom** [comment]
Исправлено
