### ISSUE TITLE
DanilovSV - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#32]
Все хорошо (для заданий 1 и 2), но нет обзора.

**Comment by SammyVimes** [comment]
Добавил и смержил.
https://github.com/moevm/scientific_writing-2017/pull/43

**Comment by zmm** [comment]
Отлично, добавьте ссылки на источники + подумайте над таким вопросом - является ли термин "бот" жаргонизмом?
