### ISSUE TITLE
AndrosovVU - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#33]
*Цель и проблема*

Необходимо сузить цель и, возможно, проблему - в вашей работе целью является не выработка универсального решения для всех онлайн-курсов, а создание автоматически проверяемых задач для конкретного подмножества MOOC.

*Актуальность*

Было  бы здорово снабдить оба утверждения подтверждающими ссылками. С первым я согласен, но вот насчет второго есть вопросы  - как минимум не всегда можно глядя снаружи на курс понять, как быстро там проверяют задачи.

**Предмет исследования**

С точки зрения планируемых результатов ваше исследование не исследует именно сами временные затраты (иначе альтернативы были бы примерно такие - использование студентов для проверки/ использование простых задач), а конкретные формы организации задач.

**Аналоги**
 
- Добавьте пожалуйста обоснования для критериев - почему именно они характеризуют отобранные аналоги в контексте данной задачи.
- "На основании имеющихся критериев, примененных к рассматриваемому списку, наиболее подходящими являются курсы:" - подходящим для чего ?

**Comment by rosshkaa** [comment]
https://github.com/moevm/scientific_writing-2017/compare/androsovvu
