### ISSUE TITLE
PutkovDA - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#34]
** Общие замечания **

Постарайтесь сократить использование оборотов, которые не проясняют сути дела + выбиваются из научного стиля, например:
- мало-мальски значимый
- иметь под рукой
- глазами пробегая

Личных форм необходимо также избегать - согласно установившимся в нашей стране академическим традициям предложения для технических статей должны быть в безличной форме.
- хотелось бы иметь под рукой -> необходим в ежедневной работе
- я ставил -> ставились были поставлены

Подробнее про научный стиль можно прочитать по ссылке http://library.unecon.ru/sites/default/files/library/pravila_dlya_molodyh_uchenyh.pdf
на странице 4 и по ссылке https://moluch.ru/information/stil-nauchnoj-stati/

**Проблема**

В описании проблемы нет необходимости добавлять информацию об актуальности (про это есть отдельный раздел) - _Сегодня каждый мало-мальски значимый проект имеет свою платформу для хранения в сети. Одной из самых популярных платформ является Github._ 

Вместо этого предлагаю описать более общую проблему и ответить на вопрос - **зачем** нужно получать такую статистику репозитория? 

**Задачи**

В данном разделе необходимо перечислить задачи вашего исследования (что нужно было сравнить/измерить/разработать), а не функциональность разработанного решения.

**Comment by PutkovDimi** [comment]
Исправленные файлы смержил в мастер

**Comment by zmm** [comment]
Приложите пожалуйста ссылки на пулл-реквесты с фиксами.

**Comment by PutkovDimi** [comment]
https://github.com/moevm/scientific_writing-2017/pull/36
