### ISSUE TITLE
BudchanDS - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#38]
**Проблема**

Формулировка проблемы слишком целенаправлена ( == похожа на цель), в то время как проблема - это скорее какое-то явление. Например в вашем случае проблемой (тем явлением, что вы хотите исследовать) является именно **криптостойкость алгоритмов отрицаемого шифрования**. 

**Актуальность**

Было бы хорошо дать какую-нибудь ссылку на статистику использования, так как для людей не знакомых с предметом не совсем понятно так ли популярен этот вид шифрования.

**Comment by DariaBudchan** [comment]
#64
