### ISSUE TITLE
KlimukKP - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#40]
** Проблема**

Давайте попробуем отделить проблему от ее актуальности, также описанной в разделе **Проблема**, так как проблема это собственно то явление, с которым мы работаем, например - процесса создания шейдеров в Unity 

**Аналоги**

В процессе подготовки финальной версии статьи вам будет необходимо детализировать (добавить более подробные объяснения) - почему у определенной альтернативы та или иная оценка по критериям, так как сами оценки (как и критерии) достаточно субъективные.

**Comment by ChivaTateo** [comment]
Дописал все. Pandoc почему-то отказался создавать мне Pdf файл, поэтому пересохранил pdf из odt. 

#98
