### ISSUE TITLE
ChaykaKV - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#41]
**Цель**

Цель "исследовать что-то" подразумевает достаточно много интерпретаций. Рекомендую ее уточнить целью конкретной задачи, в рамках которой будут работать алгоритмы и/или критериями, предъявляемыми к ним.

**Аналоги**

Для лучшего понимания читателями необходимо дать детализацию для критерия "Простота использования и конфигурации" - какой порог вхождения соответствует оценке - и какой оценке +.

Также в тексте часто встречается слово "хороший", "хорошая" - оно не соответствует научному стилю (так как это выражение субъективной позиции автора) и его рекомендуется заменить на более точные эпитеты, например:
а также хорошей поддержки - своевременной, оперативной, квалифицированной

**Comment by pro100kot** [comment]
https://github.com/moevm/scientific_writing-2017/pull/57
