### ISSUE TITLE
BleesEI - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#48]
**Цель**

Текущая формулировка цели подразумевает под собой две задачи. Постарайтесь их объединить в рамках одной, поскольку цель должна быть только одна. 

**Проблема**

Кажется, что проблема это сама по себе проверка статей (поскольку процесс сложный/трудоемкий), а не необходимость ее делать, так как иначе решение было бы довольно очевидным - отказаться от проверки. 

**Актуальность**

- Автоматизация проверки не ускоряет собственно написание статьи - она ускоряет публикацию.
- Не сказано, зачем нужно автоматизировать процесс проверки.

**Задачи**

Задачи не затрагивают явно следующую часть цели "предложить решение, позволяющее проверить научную статью по нескольким критериям".

**Аналоги**

Для лучшего понимания предметной области необходимо дать определение (можно свое/ можно дать ссылки на существующие определения) терминам SEO и "научный стиль", поскольку вы на них будете очень много опираться в дальнейшем. Без этого читателю не понять, какие именно критерии качества текста вы рассматриваете.

**Comment by EduardBlees** [comment]
#84
