### ISSUE TITLE
RazmochaevaNV - paper

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#65]
"Общий вердикт"

После исправления замечаний ниже данную статью можно подать на конференцию ППС и после дополнительного рецензирования (с участием КВ) - в Известия ЛЭТИ.

**Введение**

-  "У компаний, занимающихся розничной торговлей, часто возникает задача анализа продаж." Большая часть введений к научным статьям начинаются с подобных утверждений - общих соображений о том, как выглядит поставленная проблема. Такое утверждение задает тон всей работе и поэтому важно, чтобы оно было обоснованным (имело ссылку на статью, статистический отчет и т.д).
- "На данный момент такая задача чрезвычайно актуальна в силу того, что ее решение
отнимает у сотрудников много времени и сил" - а только ли силами сотрудников производиться этот анализ (в текущей формулировке звучит именно так)? Может быть есть и какие-нибудь инструменты ? Чем в общих чертах они "плохи"?
- "Автоматизация анализа данных и процесса формирования ассортимента позволит увеличить
скорость работы не только отдельно взятого сотрудника, но и всей компании." - данное предложение очень похоже на последнее предложение из предыдущего абзаца. Возможно, раз в них так много общего, их стоит объединить? 
-  "Использование нейронных сетей в качестве основы для системы формирования ассортимента новая область применения данного инструмента." - о каком инструменте идет речь?
- рекомендую цель поставить перед ОИ и ПИ + добавить текстовую подводку к цели, например "и поэтому цель данной работы ..."

**Обзор предметной области**

-  "группировка методов на три основные группы." 
-- похожие слова (группировка, группы)
-- из этого предложения не ясно, зачем группировать методы. Может быть их лучше вдобавок к группировке сравнить/проанализировать/охарактеризовать?
- общая рекомендация - редакторы журналов/сборников очень плохо реагируют на короткие разделы. Поэтому, я рекомендую вместо жесткого деления на группы в тексте с помощью подзаголовков, сделать деление в виде абзацев - один абзац это про Формализованные методы, другой про другие и тд. При этом важно, чтобы каждый абзац начинался с "гладкого текста".
- Методы оптимизации - из данного раздела не ясна связь рассматриваемых методов с целью работы .
- "Для сравнения аналогов выделим наиболее важные на взгляд авторов критерии оценки." - фактически только так критерии и выбираются (согласно мнению авторов), но было бы здорово упомянуть и о их связи с целью работы. 
- сами нейронные сети не упоминаются в ходе обзора - нужно либо их упомянуть, либо дать им краткую характеристику. 

**Описание метода решения**

- В первом абзаце данного раздела не хватает связи с предыдущим текстом и целью работы.
- "Рисунок 1. Общее представление о структуре нейронной сети" - кажется, что не стоит давать общее представление о работе нейронной сети в такой страницеемкой форме (в виде рисунка). Может быть его можно заменить на рисунок вашей сети (или того типа сетей, который вы хотите использовать)?
- в итоговом виде статьи я рекомендую изменить обозначения для М-1 и М-2 - обычно индексы пишут примерно так https://en.wikipedia.org/wiki/Subscript_and_superscript
- формулы для вычисления множеств товаров также необходимо оформить согласно конкретному шаблону статьи. В текущем варианте они сливаются с текстом. 
- в описании метода (равно как и в статье) не упоминается процесс обучения нейронной сети. Для большей понятности постарайтесь хотя бы мельком (но в явных формулировках) раскрыть следующие вопросы:
-- какой алгоритм обучения?
-- какие данные нужны для обучения?

**Оформление и стиль**

- В нумерованном списке на странице 1 необходимо после точки ставить заглавные буквы.
- Встречаются личные формы глаголов (_Построим_ подход к задаче формирования ..)
- обычно есть некоторая нижняя планка источников для статьи - как правило она идет от 5-10 статей в списке литературы.

**Comment by NataRazmochaeva** [comment]
Спасибо за подробные рекомендации!
Старалась учесть замечания: https://github.com/moevm/scientific_writing-2017/pull/94

**Comment by zmm** [comment]
Наталья, спасибо за оперативность!
Оформите пожалуйста статью (paper.docx/pdf) в шаблон Известий (http://www.eltech.ru/ru/universitet/izdatelstvo/izvestiya) и поставьте ей повторно **ready_for_check**.

**Comment by NataRazmochaeva** [comment]
Статьи оформлены:
https://github.com/moevm/scientific_writing-2017/pull/112
Ссылки на актуальные версии файлов:
https://github.com/moevm/scientific_writing-2017/blob/master/2381/RazmochaevaNV/paper.pdf
https://github.com/moevm/scientific_writing-2017/blob/master/2381/RazmochaevaNV/paper.docx
Спасибо!

**Comment by anyfilatov** [comment]
Замечание по оформлению: 
* нет выравнивания по ширине.
* Уточните, как правильны ссылаться на несколько источников [1,2] для меня выглядит странно, я бы поставил [1],[2]. Узнайте, как требуется в конкретном издательстве

Замечания по смыслу:

* В описании критериев анализа. Не раскрыто, что понимается под понятием нелинейности. Либо дайте ссылку на литературу на слове "нелинейность выбора ассортимента", либо поясните мысль 
* в начале третьей старницы ведётся заумное повествование о применимости нейронных сетей к _общим_ задачам, следом идёт абзац, начинающийся со слов "более того", а далее - можно считать, недостаток использования нейронных сетей в _конкретной_ области. Проще всего решить проблему заменой слов "более того" на какие-то более подходящие
* Очень неожиданно вспылвает тема "дублирования" товаров. Сначала шла речь только о выборе: добалении и удалении. Возможно, следует одним предложением раскрыть суть, чем поможет дублирование товара. Или заменить слово "дублирование" на слово "дополнение" или "увеличение объёма"

**Comment by NataRazmochaeva** [comment]
Большое спасибо за замечания!
Небольшое непонимание вызвал момент с "выравниванием по ширине". 
Шапка статьи (Перечень авторов, Название статьи, Ключевые слова) по требованиям издательства - по левому краю (https://izv.eltech.ru/ru/avtoram/pravila-oformleniya). Других случаев выравнивания "не" по ширине в статье не нашла.

**Comment by anyfilatov** [comment]
Вилимо у меня просмотрщик pdf глючит. Действительно, в docx всё правильно

**Comment by NataRazmochaeva** [comment]
Постаралась исправить все замечания:
https://github.com/moevm/scientific_writing-2017/blob/master/2381/RazmochaevaNV/paper.docx
https://github.com/moevm/scientific_writing-2017/blob/master/2381/RazmochaevaNV/paper.pdf
Спасибо!
