### ISSUE TITLE
ChulanovAA - stage 1

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#75]
### Ответы на ключевые вопросы

- Проблема должна иметь более широкую направленность, то есть быть какой-то либо четко сформулированной проблемой научного мира (сходимость интегралов над полем ...), либо отражать какое-нибудь противоречие реального мира, например: музыки в сети много, а слушать нечего . В вашем случае кажется, что ближе второй вариант.
- Цель - а нет ли общеупотребительного научного термина (Может быть из теории музыки) для тех параметров, которые вы собираетесь вычислять, либо для самой процедуры их вычисления?
- Актуальность содержит описание вашего решения как уже готового и исследованного. Традиционно в этом разделе развивают мысль, описанную в Проблеме - например указывают количество людей страдающих от нехватки хорошей музыки, приводят количество бесцельно проведенных вечеров и тд. В целом идея следующая - укажите, почему и для кого сформулированная Проблема имеет значение, чем существующие решения плохи. 

### Аналоги

- Укажите пожалуйста в тексте ссылки на ваши источники из списка литературы. Пока кажется, что они не использовались при составлении обзора, тк они не упоминаются в тексте.
- Давайте добавим перед перечислением аналогов хотя бы абзац текста про то, почему вы рассматриваете именно эти подходы/сервисы, так как они выглядят достаточно разнородно
- на приложения необходимо дать ссылки.

**Comment by Dron642** [comment]
#87
