### ISSUE TITLE
KomarovDN - stage 2-3

### ISSUE THREAD

**Issue by zmm** [moevm/scientific_writing-2017#90]
### Выбор метода решения

Часть критериев для решения является субъективными, то есть их проверка будет сильно зависить от проверяющего лица - кому-то будет интуитивно понятно, а кому-то нет. Например:
- Интуитивно понятный интерфейс
- Простота и доступность использования.
Поэтому предлагаю их  конкретизировать (как вариант "интерфейс должен воплощать концепцию material design").

### Описание метода решения

- Не хватает подрисуночных подписей к изображений и их упоминаний в тексте.
- Было бы полезно как-то прокомментировать стек технологий  - почему они были выбраны. 

### Исследование метода решения

- "Согласно цели решение предоставляет функционал," 
-- звучит не совсем благозвучно
-- кажется что цель была в другом - сокращение времени ожидания перед просмотром превью ролика

### Выводы

Приведите дальнейшие направления для работы над вашим решением - как с точки зрения продукта, так и с точки зрения исследования.

**Comment by komarkom** [comment]
https://github.com/moevm/scientific_writing-2017/pull/95
